// Copyright 2026 Amit Chorasiya. All rights reserved.
// Licensed under the Business Source License 1.1. See LICENSE file.

import SwiftUI
import AppKit

struct AIDisclaimerView: View {
    @AppStorage("hasAcceptedAIDisclaimer") private var hasAcceptedAIDisclaimer = false
    @EnvironmentObject var configManager: LLMConfigManager
    @State private var hasAgreed = false
    @State private var showSetupProgress = false
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        if showSetupProgress {
            AISetupProgressView(
                onDone: { dismiss() },
                onSkip: { dismiss() }
            )
            .environmentObject(configManager)
        } else {
            ZStack {
                Color.dsBackground.ignoresSafeArea()

                VStack(spacing: 0) {
                    header
                    disclaimerContent
                    agreementFooter
                }
                .frame(maxWidth: 650)
                .padding(.vertical, AppTheme.Spacing.xl)
            }
        }
    }

    private var header: some View {
        VStack(spacing: AppTheme.Spacing.medium) {
            Image(systemName: "brain.head.profile")
                .font(.system(size: 44))
                .foregroundStyle(.purple)
                .symbolRenderingMode(.hierarchical)

            Text("AI Features Disclaimer")
                .font(.system(size: 24, weight: .bold))
                .foregroundStyle(Color.dsPrimaryText)

            Text("Please read before using AI-powered organization features.")
                .font(.system(size: 14))
                .foregroundStyle(Color.dsSecondaryText)
                .multilineTextAlignment(.center)
        }
        .padding(.bottom, AppTheme.Spacing.large)
    }

    private var disclaimerContent: some View {
        GlassCard(padding: 0) {
            ScrollView {
                VStack(alignment: .leading, spacing: AppTheme.Spacing.large) {
                    aiAccuracySection
                    Divider()
                    dataPrivacySection
                    Divider()
                    userResponsibilitySection
                }
                .padding(AppTheme.Spacing.large)
            }
            .frame(maxHeight: 350)
        }
        .padding(.horizontal, AppTheme.Spacing.xl)
    }

    private var aiAccuracySection: some View {
        VStack(alignment: .leading, spacing: AppTheme.Spacing.medium) {
            sectionHeader("AI-Generated Suggestions")

            bulletPoint("AI suggestions are generated by large language models (LLMs) and may be inaccurate, incomplete, or inappropriate.")
            bulletPoint("The AI may misclassify files, suggest incorrect folder structures, or propose misleading file renames.")
            bulletPoint("DriveSyncAI does not use your file data to train AI models.")
        }
    }

    private var dataPrivacySection: some View {
        VStack(alignment: .leading, spacing: AppTheme.Spacing.medium) {
            sectionHeader("Data Privacy")

            HStack(alignment: .top, spacing: AppTheme.Spacing.medium) {
                Image(systemName: "lock.shield.fill")
                    .foregroundStyle(.green)
                    .font(.system(size: 18))
                VStack(alignment: .leading, spacing: 4) {
                    Text("Ollama (Local)")
                        .font(.system(size: 13, weight: .semibold))
                        .foregroundStyle(Color.dsPrimaryText)
                    Text("All processing happens on your Mac. No data leaves your device.")
                        .font(.system(size: 12))
                        .foregroundStyle(Color.dsSecondaryText)
                }
            }

            HStack(alignment: .top, spacing: AppTheme.Spacing.medium) {
                Image(systemName: "cloud.fill")
                    .foregroundStyle(.blue)
                    .font(.system(size: 18))
                VStack(alignment: .leading, spacing: 4) {
                    Text("Cloud Providers (OpenAI, Anthropic, Google, Perplexity)")
                        .font(.system(size: 13, weight: .semibold))
                        .foregroundStyle(Color.dsPrimaryText)
                    Text("File metadata (names, paths, sizes, types, document properties) is sent to third-party servers. Actual file contents are never transmitted. Your use is subject to each provider's terms of service.")
                        .font(.system(size: 12))
                        .foregroundStyle(Color.dsSecondaryText)
                }
            }
        }
    }

    private var userResponsibilitySection: some View {
        VStack(alignment: .leading, spacing: AppTheme.Spacing.medium) {
            sectionHeader("Your Responsibility")

            Text("""
                YOU ARE SOLELY RESPONSIBLE FOR REVIEWING ALL AI-GENERATED SUGGESTIONS \
                BEFORE THEY ARE EXECUTED. DRIVESYNCAI AND ITS DEVELOPER SHALL NOT BE \
                LIABLE FOR ANY DATA LOSS, FILE MISPLACEMENT, INCORRECT RENAMING, OR \
                OTHER HARM RESULTING FROM AI-SUGGESTED ACTIONS, WHETHER OR NOT YOU \
                REVIEWED SUCH SUGGESTIONS PRIOR TO EXECUTION.
                """)
                .font(.system(size: 12))
                .foregroundStyle(Color.dsSecondaryText)
                .fixedSize(horizontal: false, vertical: true)

            bulletPoint("Always review the plan before executing.")
            bulletPoint("Use dry-run mode to preview changes safely.")
            bulletPoint("Maintain backups of important data.")
        }
    }

    private var agreementFooter: some View {
        VStack(spacing: AppTheme.Spacing.large) {
            Toggle(isOn: $hasAgreed) {
                Text("I understand that AI suggestions may be inaccurate and accept full responsibility for reviewing all actions")
                    .font(.system(size: 13, weight: .medium))
                    .foregroundStyle(Color.dsPrimaryText)
            }
            .toggleStyle(.checkbox)
            .padding(.horizontal, AppTheme.Spacing.xl)

            HStack(spacing: AppTheme.Spacing.large) {
                GlassButton("Decline", icon: "xmark", style: .secondary) {
                    dismiss()
                }

                GlassButton("Accept & Set Up AI", icon: "checkmark", style: .primary, isDisabled: !hasAgreed) {
                    hasAcceptedAIDisclaimer = true
                    withAnimation(AppTheme.Animation.smooth) {
                        showSetupProgress = true
                    }
                }
            }
        }
        .padding(.top, AppTheme.Spacing.large)
    }

    private func sectionHeader(_ title: String) -> some View {
        Text(title)
            .font(.system(size: 15, weight: .semibold))
            .foregroundStyle(Color.dsPrimaryText)
    }

    private func bulletPoint(_ text: String) -> some View {
        HStack(alignment: .top, spacing: AppTheme.Spacing.small) {
            Text("\u{2022}")
                .font(.system(size: 13))
                .foregroundStyle(.purple)
                .frame(width: 12)
            Text(text)
                .font(.system(size: 13))
                .foregroundStyle(Color.dsSecondaryText)
                .fixedSize(horizontal: false, vertical: true)
        }
    }
}
